- lib/TuyaOAuth2Client.js
- lib/TuyaOAuth2DeviceLight.js
- lib/TuyaOAuth2Driver.js
- lib/TuyaOAuth2DriverLight.js
**- Fixed light data mismatch between Tuya and Homey**
The constants that were used were not always correct,
as Tuya uses the same property names with different definitions between light subclasses.
The definitions are now retrieved from the device specification,
so they should always match the device itself, independent of its class.
This fixes problems with colors etc. not matching,
but it is also a breaking change for people already testing the app with their lights.
**- Fixed an incorrect capability in pairing**
Instead of the switch_led Tuya capability bright_value was added.
This meant that devices using bright_value_v2 were sending data twice,
causing errors and making the Homey temperature picker bug out.
This fix also requires repairing lights already being tested.
**- Fixed …
> Fix light bugs

- app.json
- drivers/socket/driver.settings.compose.json
- lib/TuyaOAuth2DeviceSocket.js
Fixes #42 
**Added setting to scale socket power measurement**
Some device implementations differ from the documentation in the factor by which measured power is scaled.
Since this factor cannot reliably be retrieved from the device state or specification a setting was deemed the most straightforward fix.
> Add setting to scale socket power measurement

- .homeycompose/flow/actions/send_command_boolean.json
- .homeycompose/flow/actions/send_command_json.json
- .homeycompose/flow/actions/send_command_number.json
- .homeycompose/flow/actions/send_command_string.json
- .homeycompose/flow/triggers/receive_status_boolean.json
- .homeycompose/flow/triggers/receive_status_json.json
- .homeycompose/flow/triggers/receive_status_number.json
- .homeycompose/flow/triggers/receive_status_string.json
- app.json
- drivers/other/device.js
- lib/TuyaOAuth2App.js
- lib/TuyaOAuth2Client.js
- lib/TuyaOAuth2Device.js
- lib/TuyaOAuth2Util.js
**Added 'other' devices to webhook registration**
A separate register of 'other' devices is kept, so that devices with dedicated drivers can also be added as 'other' without breaking them.
**Added flow cards for receiving Tuya statuses**
These trigger flow cards match the existing action flows, supporting numbers, booleans, strings and JSON.
Since Tuya sometimes encodes JSON twice strings are also checked for JSON format, with the action card updated to do the same.
> Improve unknown device functionality

- lib/TuyaOAuth2DeviceSocket.js
- lib/TuyaOAuth2DriverSocket.js
**Fix socket for out-of-spec switch capability**
Some sockets use the 'switch' Tuya capability for a single switch, instead of 'switch_1'.
This fix now gives these devices the 'onoff' capability
**Refactored socket switch detection**
For ease of maintenance, duplicate code was refactored.
May fix:
- #79 
- #93
> Fix socket for out-of-spec switch capability

- .homeycompose/locales/en.json
- app.json
- drivers/light/driver.flow.compose.json
- drivers/light/driver.settings.compose.json
- lib/TuyaLightConstants.js
- lib/TuyaOAuth2Constants.js
- lib/TuyaOAuth2DeviceLight.js
- lib/TuyaOAuth2DriverLight.js
- locales/en.json
**- Added support for motion lights**
The following capabilities were implemented and tested:
motion_alarm (pir_state)
The following settings were implemented and tested:
Motion Detection (switch_pir)
Motion Sensitivity (pir_sensitivity)
Motion Delay (pir_delay)
Luminance Detection: (cds)
Standby Light (standby_on)
Standby Time (standby_time)
Standby Brightness (standby_bright)
The test device did not have "standby_on", but emulated it by setting standby_bright to 0.
This is mimicked by the "Standby Light" setting when "standby_on" is not present.
**- Fixed light data ranges**
Some devices do not report their ranges. Since all categories, except for "dj", use the same values,
defaults were added based on the Tuya documentation.
**- Fixed dim implementation**
Lights that do not support …
> Expand lights

- app.json
- drivers/light/driver.flow.compose.json
- lib/TuyaOAuth2DeviceLight.js
- lib/TuyaOAuth2DriverLight.js
- lib/migrations/TuyaLightMigrations.js
**Fixed lights for out-of-spec switch capability**
Some lights appear to use the 'switch' Tuya capability alongside or instead of 'switch_led'.
These devices are now handled the same way as sockets, with a single Tuya capability resulting only in the 'onoff' Homey capability, and both capabilities resulting in two sub-capabilities and the 'onoff' capability toggling both.
**Added a migration for the fix**
Since the 'switch' capability was not handled during pairing previously a migration was added to add it to existing devices, as well as keep existing devices that don't need the fix working with the new handlers.
Since devices were sometimes synchronized before the onOAuth2Init had finished, a barrier was also added to prevent invalid states and devices becoming unavailable due to …
> Fix lights for out-of-spec switch capability

- lib/TuyaOAuth2DriverFan.js
**Quick fix fan dim capability range**
The range of the dim capability defined max twice, instead of a min and a max.
Since the documentation says the range should be [1, 100] the device specification is now also used if present.
Since I don't have a test device the default was left as is, being [1, 6], but this should be looked at at some point.
> Quick fix fan dim capability range

- app.json
- drivers/fan/driver.compose.json
- drivers/light/driver.compose.json
- drivers/sensor_contact/driver.compose.json
- drivers/sensor_motion/driver.compose.json
- drivers/sensor_smoke/driver.compose.json
- drivers/socket/driver.compose.json
**Add a generic set of capabilities to each driver.compose**
Added a few basic capabilities that most represent each device to their respective driver.compose.json files.
This ensures that the store page of the app shows some applicable flows to give an impression of what devices can do.
> Add a generic set of capabilities to each driver.compose

- .homeycompose/locales/en.json
- app.json
- drivers/socket/driver.flow.compose.json
- drivers/socket/driver.settings.compose.json
- lib/TuyaOAuth2DeviceSocket.js
- lib/TuyaOAuth2DriverSocket.js
- lib/TuyaOAuth2Util.js
- lib/TuyaSocketConstants.js
- locales/en.json
**Added socket settings**
Added the 'child_lock' and 'relay_status' Tuya capabilities as settings, with an action flow for the child lock.
**Added reusable setting handlers**
Since the new onSettings would need similar code as found in other handlers,
a few reusable handlers were added in TuyaOAuth2Util.
The similar handlers can be refactored to use these at a later point.
**Fixed socket sub-switch flow runListeners**
Errors in the action flows for sub-sockets were caught, meaning the flow card succeeded on an error.
Now a user-friendly error is thrown instead, with the original error being logged.
> Add socket settings

- drivers/dimmer/driver.js
- drivers/heater/driver.js
- lib/TuyaOAuth2Driver.js
- lib/TuyaOAuth2DriverLight.js
Ignore failures retrieving the specification, and handle a missing value gracefully. Might be related to #129 and #131.
> Handle missing specifications gracefully

- lib/TuyaOAuth2Client.ts
**- Fixed malformed json in sendCommands**
The object surrounding the commands being sent was lost during a refactor. It has been added again.
> Fix malformed json in sendCommands

- drivers/light/driver.ts
- lib/migrations/TuyaLightMigrations.ts
**- Fixed setondim for lights with other switch**
In lights with another switch in addition to the light, turning the light on or off using the dim capability also turns the other switch on or off.
To prevent his setOnDim is now false if multiple onoff capabilities are used.
A migration fixes this for existing devices.
> Fixed setondim for lights with other switch

- .homeycompose/flow/triggers/receive_status_boolean.json
- .homeycompose/flow/triggers/receive_status_json.json
- .homeycompose/flow/triggers/receive_status_number.json
- .homeycompose/flow/triggers/receive_status_string.json
- app.json
- app.ts
- lib/TuyaOAuth2Client.ts
- lib/TuyaOAuth2Device.ts
**- Added data points to send_command and receive_status flows**
Since not all devices map their data points to the standard instruction/status set some functionality was unavailable for control.
Data points are now also retrieved and added to the options of send_command and receive_status flows if they are not available from the status yet. Since it is not guaranteed that the device will actually report these data points a warning was added to the receive_status hint.
> Add data points to send_command flows

- .homeycompose/drivers/settings/alarmTimeout.json
- .homeycompose/drivers/settings/useAlarmTimeout.json
- app.json
- drivers/camera/device.ts
- drivers/camera/driver.settings.compose.json
- drivers/sensor_contact/device.ts
- drivers/sensor_contact/driver.settings.compose.json
- drivers/sensor_motion/device.ts
- drivers/sensor_motion/driver.settings.compose.json
- drivers/sensor_motion/driver.ts
- drivers/sensor_smoke/device.ts
- drivers/sensor_smoke/driver.settings.compose.json
- drivers/sensor_smoke/driver.ts
- lib/TuyaOAuth2Client.ts
- lib/TuyaOAuth2Device.ts
- lib/TuyaOAuth2DeviceSensor.ts
- lib/TuyaTimeOutAlarmDevice.ts
**- Fixed sensor reset**
Some sensors never send an end signal, leaving the alarm perpetually triggered.
A setting has been added to allow timeouts to end sensor alarms without an end signal.
This setting is automatically set when adding motion or smoke sensors based on their specification.
Since contact sensors use a boolean it is not possible to do this.
> Fixed sensor reset

- app.json
- drivers/dimmer/TuyaDimmerConstants.ts
- drivers/dimmer/device.ts
- drivers/dimmer/driver.flow.compose.json
- drivers/dimmer/driver.settings.compose.json
- drivers/dimmer/driver.ts
#163 added the `tgkg` category to our dimmer driver, but did not add support for the possible third channel. This PR add support for that third channel as described in https://developer.tuya.com/en/docs/iot/s?id=K9t2a5mn56bdr.
> Add support for third dimmer channel

- drivers/fan/driver.ts
- drivers/light/driver.ts
- lib/migrations/TuyaLightMigrations.ts
- **Fixed assumption that fan specifications are defined**
Some fan devices give malformed specifications, resulting in not being able to add fans.
In these cases the default specifications from the Tuya documentation are now assumed.
- **Added migration to fix undefined light specifications**
Some lights added in older versions may be missing some specifications, and never received them since.
A migration was added to ensure every existing light has these values set.
> 1.3.0 Fixes

- drivers/heater/device.ts
- drivers/sensor_climate/device.ts
- drivers/socket/device.ts
- lib/TuyaOAuth2Util.ts
- **Change current capability value when changing scale factor**
When changing scaling factors in settings the capability value now immediately uses the new scale, instead of having to wait for a new value.
Fixes https://github.com/athombv/com.tuya/issues/196
> Change current capability value when changing scale factor

- app.json
- drivers/camera/TuyaCameraConstants.ts
- drivers/camera/device.ts
- drivers/dimmer/TuyaDimmerConstants.ts
- drivers/dimmer/device.ts
- drivers/fan/device.ts
- drivers/heater/driver.settings.compose.json
- drivers/light/TuyaLightConstants.ts
- drivers/light/device.ts
- drivers/light/driver.ts
- drivers/sensor_climate/TuyaClimateSensorConstants.ts
- drivers/siren/TuyaSirenConstants.ts
- drivers/siren/device.ts
- **Fixed setting types**
Some types for device settings were not up to date, or missing altogether. The missing settings have been added, and setting handlers updated accordingly.
- **Migrated dimmer and light setting handlers**
These drivers now use the setting handler in utils, instead of their own slightly different duplicate of the code.
> Settings maintenance

- .homeycompose/flow/triggers/child_lock_false.json
- .homeycompose/flow/triggers/child_lock_true.json
- app.json
- **Fixed child lock flow filters**
Some drivers that support the child lock capability were missing from the flows for that capability.
This is no fixed.
> Fix child lock flow filters

- lib/TuyaOAuth2Device.ts
- lib/webhooks/TuyaWebhookParser.ts
- types/TuyaTypes.ts
No longer use the webhook data id to deduplicate data, as it seems that the data from the status webhook needs to take precedence.
> Handle webhook data deduplication in device implementation
